Update code to comply with WP Coding Standards (rebased)
markcheret/footnotes pull request #32
Opened 2021-02-21 18:48 UTC by Rumperuu

Updates the codebase to ensure compliance with the WP Coding Standards.

Also composerises the project to allow for the installation of a pre-commit PHP_CodeSniffer hook (and other hooks later on).

**This is a duplicate of #23, except rebased to separate commit https://github.com/markcheret/footnotes/pull/23/commits/3a44a194994763ef2f6370f1cd3aa0d7d22f8a7e into two different commits (https://github.com/markcheret/footnotes/commit/27abf833941a2a5921f71e79f7248a57876210b5 and https://github.com/markcheret/footnotes/commit/b349544fc26b2f2608a6a03d782f0ebf9f26fb3a), ensuring that `class/dashboard/` and its files are properly tracked as having been renamed to `class/layout`, rather than deleted.**

Replace #23 

Close #8
Close #10
Close #11

2021-02-21 18:50 UTC, Rumperuu commented
Reposting @pewgeuges's comment from #23:

> Hi, As reported in an urgent thread, it’s now broken, sorry. Sure you will get it to work again, but honestly I don’t see the point in doing all this WP compliance stuff. They don’t give us anything for it, and I even suspect they think much good. There is zero benefit for our users, while developers are impacted by the unwieldy variable names. Moreover, snakecase is harder to type on a QWERTY, as you need to not only press shift, but reach out to the minus key instead of keeping type the name. The underscores are designed for Hungarian to stay readable, while the name should be one piece. Should I spend all the time now commenting on GitHub, or is it fine by email? Sorry for duplicate addressees. Cheers, Marcel
> […](#)
> On Sun, Feb 21, 2021 at 5:52 PM Rumperuu ***@***.***> wrote: Going to leave this on draft until I've had a chance to test that everything is still working as before (I had to do a *lot* of RegEx wizardry) — You are receiving this because your review was requested. Reply to this email directly, view it on GitHub <[#23 (comment)](https://github.com/markcheret/footnotes/pull/23#issuecomment-782887723)>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AROA25HJVF7NYEJX3RMWBU3TAE23BANCNFSM4X62E6DA> .

2021-02-21 19:26 UTC, pewgeuges commented
Thanks Rumperuu for re-posting.
The deleted comment from Rumperuu was only my feedback by email sent to the previous branch #23 and that I deleted there after changing my mind. Meanwhile mirrored here, hence deleted again as out of sync with the ongoing review.

2021-02-21 19:57 UTC, Rumperuu commented
Tried rebasing to the new `main` but it seems to have gone a bit squiffy. No damage done, just an ugly patch of commit history.

2021-02-21 21:21 UTC, Rumperuu commented
Ah! I was trying to be too clever with all of my double-wildcarding and accidentally ignored the `widget/` and `layout/` directories :man_facepalming: 

Command updated in README and those files are now ALMOST fixed - just need to add nonce verification now

2021-02-21 21:57 UTC, Rumperuu commented on class/config.php
> +class MCI_Footnotes_Config {
Hey @pewgeuges, line 20 of `class/config.php` is where the party is!

2021-02-21 21:58 UTC, Rumperuu commented on class/config.php
> +class MCI_Footnotes_Config {
:partying_face:

2021-02-21 22:30 UTC, Rumperuu commented
> Ah! I was trying to be too clever with all of my double-wildcarding and accidentally ignored the `widget/` and `layout/` directories man_facepalming
> 
> Command updated in README and those files are now ALMOST standards-compliance now - just need to add nonce verification.
> 
> Still getting this error when activating the Plugin though, so fixing that first:
> 
> > Fatal error: Uncaught Error: Class 'MCI_Footnotes_Layout_Engine' not found in /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/class/layout/diagnostics.php:15 Stack trace: #0 /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/includes.php(32): require_once() #1 /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/includes.php(38): mci_footnotes_require_php_files('/srv/www/wordpr...') #2 /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/footnotes.php(55): require_once('/srv/www/wordpr...') #3 /srv/www/wordpress-one/public_html/wp-admin/includes/plugin.php(2299): include('/srv/www/wordpr...') #4 /srv/www/wordpress-one/public_html/wp-admin/plugins.php(191): plugin_sandbox_scrape('footnotes/footn...') #5 {main} thrown in /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/class/layout/diagnostics.php on line 15

Broken as of bb3b555

2021-02-21 23:07 UTC, Rumperuu commented
> > Ah! I was trying to be too clever with all of my double-wildcarding and accidentally ignored the `widget/` and `layout/` directories man_facepalming
> > Command updated in README and those files are now ALMOST standards-compliance now - just need to add nonce verification.
> > Still getting this error when activating the Plugin though, so fixing that first:
> > > Fatal error: Uncaught Error: Class 'MCI_Footnotes_Layout_Engine' not found in /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/class/layout/diagnostics.php:15 Stack trace: #0 /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/includes.php(32): require_once() #1 /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/includes.php(38): mci_footnotes_require_php_files('/srv/www/wordpr...') #2 /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/footnotes.php(55): require_once('/srv/www/wordpr...') #3 /srv/www/wordpress-one/public_html/wp-admin/includes/plugin.php(2299): include('/srv/www/wordpr...') #4 /srv/www/wordpress-one/public_html/wp-admin/plugins.php(191): plugin_sandbox_scrape('footnotes/footn...') #5 {main} thrown in /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/class/layout/diagnostics.php on line 15
> 
> Broken as of [bb3b555](https://github.com/markcheret/footnotes/commit/bb3b55514829dda0e61f038e8c8844c3ae656d86)

Fixed in 6eda55d

After painstakingly comparing every diff from bb3b555 line-by-line, I realised that the reason it was failing is because `includes.php` `require_once()`s files alphabetically per-directory, so by renaming `layout.php` to `engine.php` and `subpage-diagnostics.php` to `diagnostics.php` I can accidentally thrown off the order. Temporarily fixed by renaming `engine.php` to `abstract-engine.php`, but really we should refactor `includes.php` to be smarter when we get the chance.

2021-02-22 00:25 UTC, pewgeuges commented
Congrats for the fix!

On Mon, Feb 22, 2021 at 12:07 AM Rumperuu <notifications@github.com> wrote:

> Ah! I was trying to be too clever with all of my double-wildcarding and
> accidentally ignored the widget/ and layout/ directories man_facepalming
> Command updated in README and those files are now ALMOST
> standards-compliance now - just need to add nonce verification.
> Still getting this error when activating the Plugin though, so fixing that
> first:
>
> Fatal error: Uncaught Error: Class 'MCI_Footnotes_Layout_Engine' not found
> in
> /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/class/layout/diagnostics.php:15
> Stack trace: #0
> /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/includes.php(32):
> require_once() #1 <https://github.com/markcheret/footnotes/pull/1>
> /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/includes.php(38):
> mci_footnotes_require_php_files('/srv/www/wordpr...') #2
> <https://github.com/markcheret/footnotes/pull/2>
> /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/footnotes.php(55):
> require_once('/srv/www/wordpr...') #3
> <https://github.com/markcheret/footnotes/pull/3>
> /srv/www/wordpress-one/public_html/wp-admin/includes/plugin.php(2299):
> include('/srv/www/wordpr...') #4
> <https://github.com/markcheret/footnotes/pull/4>
> /srv/www/wordpress-one/public_html/wp-admin/plugins.php(191):
> plugin_sandbox_scrape('footnotes/footn...') #5
> <https://github.com/markcheret/footnotes/issues/5> {main} thrown in
> /srv/www/wordpress-one/public_html/wp-content/plugins/footnotes/class/layout/diagnostics.php
> on line 15
>
> Broken as of bb3b555
> <https://github.com/markcheret/footnotes/commit/bb3b55514829dda0e61f038e8c8844c3ae656d86>
>
> Fixed in 6eda55d
> <https://github.com/markcheret/footnotes/commit/6eda55d6756d0677b6b69ffadd6ce0e909707c47>
>
> After painstakingly comparing every diff from bb3b555
> <https://github.com/markcheret/footnotes/commit/bb3b55514829dda0e61f038e8c8844c3ae656d86>
> line-by-line, I realised that the reason it was failing is because
> includes.php require_once()s files alphabetically per-directory, so by
> renaming layout.php to engine.php and subpage-diagnostics.php to
> diagnostics.php I can accidentally thrown off the order. Temporarily
> fixed by renaming engine.php to abstract-engine.php, but really we should
> refactor includes.php to be smarter when we get the chance.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/markcheret/footnotes/pull/32#issuecomment-782945405>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AROA25A3BMSWGSIGVXRGL5TTAGG2TANCNFSM4X7IDV4Q>
> .
>

2021-02-22 13:50 UTC, markcheret approved these changes
thanks for adding all contributors back in

2021-02-22 18:34 UTC, Rumperuu commented on class/task.php
> +		return $this->exec( $p_str_content, false, ! MCI_Footnotes_Convert::to_bool( MCI_Footnotes_Settings::instance()->get( MCI_Footnotes_Settings::C_BOOL_FOOTNOTES_IN_EXCERPT ) ) );
@pewgeuges Will leave this for now (as it's arguably outside the scope of this branch), but I'll explain what I was doing and we can sort it out later:

`MCI_Footnotes_Convert::to_bool` is not necessary, as PHP comes with type conversion (`(bool) <variable>`) built-in. The double-not-operator (`! !`) is a shorthand was of saying that, as the first `!` automatically converts the variable into a `bool` if it was not already, and then the second `!` undoes the negation. So for example:

```
$foo = 'true';
$bar = ! $foo; // $bar === false, as 'true' is a truthy value and automatically cast to `false`
$bar = ! ! $foo; // $bar === true, as 'true' is cast to `true`, negated to `false` and then negated again back to `true`
```
So `$bar = ! ! $foo` is the same as `$bar = (bool) $foo` which is the same as `$bar = MCI_Footnotes_Convert::to_bool($foo)`. More info [here](https://stackoverflow.com/questions/2127260/double-not-operator-in-php).

On reflection, `(bool) $foo` is the most obvious so we should refactor `MCI_Footnotes_Convert::to_bool()` out in future, but no need to now as it functions fine, it's just unnecessary.

2021-02-22 18:45 UTC, Rumperuu commented
Added note to PR body about commit squash after I [started going out-of-scope](https://github.com/markcheret/footnotes/pull/32#discussion_r580492899).

2021-02-22 19:14 UTC, Rumperuu commented on class/task.php
> +		return $this->exec( $p_str_content, false, ! MCI_Footnotes_Convert::to_bool( MCI_Footnotes_Settings::instance()->get( MCI_Footnotes_Settings::C_BOOL_FOOTNOTES_IN_EXCERPT ) ) );
The advantage of using `(bool)` is doubly obvious considering the original test was `! MCI_Footnotes_Convert::to_bool()` so I should have only had the one `!` !

2021-02-22 19:18 UTC, pewgeuges commented on class/task.php
> +		return $this->exec( $p_str_content, false, ! MCI_Footnotes_Convert::to_bool( MCI_Footnotes_Settings::instance()->get( MCI_Footnotes_Settings::C_BOOL_FOOTNOTES_IN_EXCERPT ) ) );
Thanks @Rumperuu! Sorry for this commit.

2021-02-23 11:23 UTC, Rumperuu commented on class/init.php
> -				true
Good spot @pewgeuges!

2021-02-23 11:27 UTC, Rumperuu commented on class/init.php
> +				true
This should be `false`, fixed by @pewgeuges in 9226a40

2021-02-23 13:15 UTC, markcheret approved these changes
This is only a test comment. Thanks for your work

2021-02-23 13:20 UTC, markcheret commented
> This is only a test comment. Thanks for your work

another test

2021-02-23 15:15 UTC, pewgeuges requested changes
This GitHub thing is totally unusable on this branch. The plethora of mostly duplicated commits due to bugs on the platform is hard to review in detail, while the changed files view is worthless. It just shows all files with changes in them, and is unable to detect the many identical strings. @Rumperuu did not move blocks of code, so the useless diff view is the sole responsibility of the platform. Note that all space indentation was already converted back to tabs! So the code is fully diffable, but the platform is failing.

As we must track deleted docblocks and disruptive changes to the code. I cannot approve until I’ve diffed all changed files locally in VSCode.

That will take some time, and over this we should add all the missing docblocks as well, since we’re on it and so much is already fixed (or broken).

2021-02-23 15:29 UTC, Rumperuu commented on class/init.php
> +				true
Fixed in 9226a40

2021-02-23 15:38 UTC, Rumperuu commented on class/task.php
>  	 *
Should have been clearer; they don't need to be `public` class variables as they are never used outside of this class (and `private` class variables don't need docblock comments, so we can return to the previous grouping of variables under a single explanatory comment — adding temporary docblocks to each variable was needed to pass the WP Coding Standard check)

2021-02-23 15:44 UTC, Rumperuu commented
> This GitHub thing is totally unusable on this branch. The plethora of mostly duplicated commits due to bugs on the platform is hard to review in detail, while the changed files view is worthless. It just shows all files with changes in them, and is unable to detect the many identical strings. @Rumperuu did not move blocks of code, so the useless diff view is the sole responsibility of the platform. Note that all space indentation was already converted back to tabs! So the code is fully diffable, but the platform is failing.
> 
> As we must track deleted docblocks and disruptive changes to the code, I cannot approve until I’ve diffed all changed files locally in VSCode.
> 
> That will take some time, and over this we should add all the missing docblocks as well, since we’re on it and so much is already fixed (or broken).

You're right - the indentation isn't the issue. It's newlines. Will update in a sec

2021-02-23 16:05 UTC, markcheret commented
Do you need to rebase again?

2021-02-23 16:13 UTC, Rumperuu commented
> Do you need to rebase again?

It's working locally now:

```
rumperuu@ben-desktop:footnotes$ git diff main includes.php
diff --git a/includes.php b/includes.php
index 732cfb9..9501097 100644
--- a/includes.php
+++ b/includes.php
@@ -3,36 +3,37 @@
  * Includes all common files.
  *
  * @filesource
- * @author Stefan Herndler
+ * @package footnotes
  * @since 1.5.0 14.09.14 13:40
```

I think the GitHub one might have some caching so it might take a while to update.

2021-02-23 16:56 UTC, Rumperuu commented
> > Do you need to rebase again?
> 
> It's working locally now:
> 
> ```
> rumperuu@ben-desktop:footnotes$ git diff main includes.php
> diff --git a/includes.php b/includes.php
> index 732cfb9..9501097 100644
> --- a/includes.php
> +++ b/includes.php
> @@ -3,36 +3,37 @@
>   * Includes all common files.
>   *
>   * @filesource
> - * @author Stefan Herndler
> + * @package footnotes
>   * @since 1.5.0 14.09.14 13:40
> ```
> 
> I think the GitHub one might have some caching so it might take a while to update.

Not a caching issue; I think it's still diffing this branch with the version of `main` that it was branched from rather than the current version (with the line endings), so rather than mess around trying to rebase again I've just recreated the branch and created a new PR at #38 

Closing this PR

2021-02-23 16:56 UTC, closed without merging