Update code to comply with WP Coding Standards (third time's the charm!)
markcheret/footnotes pull request #38
Opened 2021-02-23 16:54 UTC by Rumperuu

### Description of Changes

Updates the codebase to ensure compliance with the [WP Coding Standard](https://duckduckgo.com/?t=canonical&q=wp+coding+standard&ia=web).

Also Composerises the project to allow for the installation of a pre-commit PHP_CodeSniffer hook (as well as other hooks later on).

### History

This is a copy of #32 that hopefully fixes the [line ending-related issue](https://github.com/markcheret/footnotes/pull/32#issuecomment-784295827) that was making the ‘Files Changed’ tab useless (and by extension making code review almost impossible).

The commits from that branch have been squashed here, but that's fine as I was originally going to squash the branch on merge anyway.

### Additional Notes

This branch's commit history will be squashed on merge, so do not make any commits to this branch that you're going to want to remain in the project history. Keep it scoped to WP Coding Standards compliance _only_.

### Actions

Replace #32 

Close #8
Close #10
Close #11

2021-02-23 17:03 UTC, Rumperuu commented
I'm hoping to get this finished off and ready for review by the end of today so that it can stop blocking all other development.

2021-02-23 17:44 UTC, pewgeuges commented
@Rumperuu Thank you for the fix. Seems the issue must be addressed at developers’ end (as opposed to the diff tool disregarding line end format).

2021-02-23 18:17 UTC, Rumperuu commented
I am confident that this is now working as normal on my test environment, ready for review.

2021-02-23 18:24 UTC, Rumperuu commented on class/hooks.php
> +			wp_die( wp_kses_post( __( 'You do not have permission to run this script.', 'footnotes' ) ) );
The second argument of `__()` must be a string literal, so having the `C_STR_PLUGIN_NAME` constant in there throws a linting error.

2021-02-23 18:36 UTC, Rumperuu commented on class/task.php
> +	public static $a_bool_tooltips_enabled = false;
These should be private, but I'll sort that out later once this PR is merged

2021-02-23 18:45 UTC, Rumperuu commented on class/task.php
> +	public static $a_bool_alternative_tooltips_enabled = false;
These (and some other class properties) should be `private`, but I'll sort that out later once this PR is merged

2021-02-23 18:46 UTC, Rumperuu commented on class/task.php
> +	 * Footnote delimiter syntax validation.
Ditto previous comment

2021-02-23 18:58 UTC, Rumperuu reviewed
Code looks good to me

2021-02-23 18:58 UTC, Rumperuu commented on class/template.php
> - * @lastmodified 2021-02-18T2024+0100
TODO: re-add comment block

2021-02-23 18:58 UTC, Rumperuu commented on footnotes.php
> +// phpcs:disable Squiz.Commenting.FileComment.MissingPackageTag
I assume the root file needs to start with this format of docblock (i.e., no `@foo` tags) in order for WordPress to be happy?

2021-02-23 18:58 UTC, Rumperuu commented on includes.php
> +function mci_footnotes_require_php_files( $p_str_directory ) {
I've left the other `MCI_Footnotes`’ capitalised as they are class names, but this is a function.

2021-02-23 21:11 UTC, pewgeuges requested changes
@Rumperuu Thank you! I’m reviewing the changed files view and committing edits alongside; sorry for not seeing your messages.

As you state, we need to review all changes in detail; I’m also correcting mistakes of my own.

2021-02-23 21:24 UTC, pewgeuges commented
> Also, I'll need to have a think about the best way to handle the output escaping warnings. Currently they're either disabled or I've put in `wp_kses_post()` or similar, but I'm not sure either of those is the best solution. Another job for later though.

Forgot to escape user-input settings values such as the reference container label, read-on button label, backlink tooltip text a.s.o. Many strings escaped so far come in from selections w/o user input; escaping these is not needed, except in the expectation that later on, settings will be added such as the already existing “Your input overrides the selection.”

> 
> The files in `class/layout/` may have to be diffed against the former files in `class/dashboard/` manually.

Okay.

> 
> There's a couple typos in comments as a result of some of my RegEx wizardry; these are fine to merge.

Already restored the ArgumentCountError compiler keyword.

I’ll respond to your other comments.

2021-02-23 21:27 UTC, pewgeuges commented on class/hooks.php
> +			wp_die( wp_kses_post( __( 'You do not have permission to run this script.', 'footnotes' ) ) );
> Explanation: the second argument of `__()` must be a string literal, so having the `C_STR_PLUGIN_NAME` constant in there throws a linting error.

Is that a performance issue?

2021-02-23 21:30 UTC, pewgeuges commented on class/task.php
> +	public static $a_bool_alternative_tooltips_enabled = false;
> These (and some other class properties) should be `private`, but I'll sort that out later once this PR is merged

These are intended to be assigned in class/init.php only, for use also in class/task.php. Then they must be public.

But they’re still assigned again there, because of possible priority level issues that need thorough testing.

2021-02-23 21:34 UTC, pewgeuges commented on class/task.php
> +	 * Footnote delimiter syntax validation.
> Ditto previous comment

Here you are correct, these are not used elsewhere. But wait: What if every big function is extracted?

2021-02-23 21:45 UTC, pewgeuges commented on class/template.php
> - * @lastmodified 2021-02-18T2024+0100
Thank you for your concern. I left only these two @since lines here, and all others down in their place, to streamline some redundancies. The file-level docblock was bloated with quickly thrown mentions, datestamps, links, pre-dating the now applied documentation schema. Searching these two changelog item strings in the files takes you down to the relevant docblock acknowledging @misfist’s thorough editing and contributing this file as-was for 2.4.0 and 2.5.0 (and later).

So I think the file-level docblock in class/template.php is okay now. Or do you see that it should contain more information?

2021-02-23 21:51 UTC, pewgeuges commented on footnotes.php
> +// phpcs:disable Squiz.Commenting.FileComment.MissingPackageTag
I’ll restore the main docblock as it was, which was fine per https://developer.wordpress.org/plugins/plugin-basics/header-requirements/

2021-02-24 08:52 UTC, Rumperuu commented on footnotes.php
> +// phpcs:disable Squiz.Commenting.FileComment.MissingPackageTag
Have added a `@package` tag in b339fd9 so that the PHPCS rule disables can both go

2021-02-24 08:53 UTC, Rumperuu reviewed
Changes made, @pewgeuges or @markcheret to approve for change (I can't as I'm the pull request author)

2021-02-24 09:52 UTC, pewgeuges commented
> Changes made, @pewgeuges or @markcheret to approve for merge (I can't as I'm the pull request author)
> 
> NB: if you're going to merge it yourself, please squash the commit history whilst doing so. If you don't know how to do that then leave it to me

No worries, won’t merge. Busy reviewing.

2021-02-24 11:01 UTC, pewgeuges commented
@Rumperuu: Review and patches could be faster if:
1. We knew that pasting files from VSCode in the GitHub web editor won’t mess up ends of line.
2. GitHub didn’t disable password authentication. Now that they did, the beautiful Git CLI is useless for commits.

2021-02-24 11:03 UTC, markcheret commented
> 2. GitHub didn’t disable password authentication. Now that they did, the beautiful Git CLI is useless for commits.
Are you using SSH or HTTPS? If you use HTTPS it should be easier to use Git CLI. Otherwise you need to install an authenticatoin provider.

2021-02-24 11:53 UTC, Rumperuu commented
> @Rumperuu: Review and patches could be faster if:
> 
>     1. We knew that pasting files from VSCode in the GitHub web editor won’t mess up ends of line.
> 
>     2. GitHub didn’t disable password authentication. Now that they did, the beautiful Git CLI is useless for commits.

No probs, it's easy to set up SSH auth — see [here](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for how to generate a key on Linux and [here](https://docs.github.com/en/enterprise-server@2.22/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account) for how to upload it to GitHub

2021-02-24 11:56 UTC, pewgeuges commented
> > 1. GitHub didn’t disable password authentication. Now that they did, the beautiful Git CLI is useless for commits.
> 
> Are you using SSH or HTTPS to clone the repo? If you use HTTPS it should be easier to use Git CLI. Otherwise you need to install an authenticatoin provider.

I’m using HTTPS and it runs smoothly, but when I try to commit, I get an email explaining that they’re switching to something else for authentication. 

Will check @Rumperuu’s links. Thanks.

2021-02-24 11:56 UTC, markcheret commented
> > @Rumperuu: Review and patches could be faster if:
> 
> > 
> 
> >     1. We knew that pasting files from VSCode in the GitHub web editor won’t mess up ends of line.
> 
> > 
> 
> >     2. GitHub didn’t disable password authentication. Now that they did, the beautiful Git CLI is useless for commits.
> 
> 
> 
> No probs, it's easy to set up SSH auth — see [here](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for how to generate a key on Linux and [here](https://docs.github.com/en/enterprise-server@2.22/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account) for how to upload it to GitHub

Yes. Passwordless authentication is the future anyway. I use a hardware token to authenticate with GitHub.

2021-02-24 12:04 UTC, pewgeuges commented
> No probs, it's easy to set up SSH auth — see [here](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for how to generate a key on Linux
Sadly this does not work: `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"` are “too many arguments”, ssh-keygen reports.

2021-02-24 12:05 UTC, pewgeuges commented
>I use a hardware token to authenticate with GitHub.

Hardware?

2021-02-24 12:36 UTC, Rumperuu commented
> > No probs, it's easy to set up SSH auth — see [here](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for how to generate a key on Linux
> 
> Sadly this does not work: `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"` are “too many arguments”, ssh-keygen reports.

Try `ssh-keygen -t ed25519 -C "your_email@example.com"` (the `-b` argument is only needed on legacy systems).



> > I use a hardware token to authenticate with GitHub.
> 
> Hardware?

Something like a [YubiKey](https://www.yubico.com/why-yubico/for-individuals/).

2021-02-24 12:37 UTC, markcheret commented
> > > No probs, it's easy to set up SSH auth — see [here](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for how to generate a key on Linux
> > 
> > 
> > Sadly this does not work: `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"` are “too many arguments”, ssh-keygen reports.
> 
> Try `ssh-keygen -t ed25519 -C "your_email@example.com"` (the `-b` argument is only needed on older systems).
> 
> > > I use a hardware token to authenticate with GitHub.
> > 
> > 
> > Hardware?
> 
> Something like a [YubiKey](https://www.yubico.com/why-yubico/for-individuals/).

Yes, exactly.

2021-02-24 12:53 UTC, pewgeuges commented
> Alternatively, did you definitely use `-C` (rather than `-c`)? See [here](https://stackoverflow.com/questions/7317863/when-i-enter-ssh-keygen-t-rsa-c-youremail-com-in-git-it-gives-too-many-arg).

No, sorry please. Just suspected I should change something in my command string, looked up the output and noticed that `-C` is an option, but I forgot the hyphen!
Added the hyphen and it works. 

Then hurried  to edit my reply, but first checked if you already answered it.

Thanks a lot! I’ve got my key.

2021-02-24 14:19 UTC, pewgeuges commented
> > @Rumperuu: Review and patches could be faster if:
> > ```
> > 1. We knew that pasting files from VSCode in the GitHub web editor won’t mess up ends of line.
> > 
> > 2. GitHub didn’t disable password authentication. Now that they did, the beautiful Git CLI is useless for commits.
> > ```
> 
> No probs, it's easy to set up SSH auth — see [here](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for how to generate a key on Linux and [here](https://docs.github.com/en/enterprise-server@2.22/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account) for how to upload it to GitHub

Steps completed, Committing/pushing via Git CLI now works. Thank you!

Sorry for writing #‌2.

2021-02-24 15:00 UTC, pewgeuges commented on class/hooks.php
> +			wp_die( wp_kses_post( __( 'You do not have permission to run this script.', 'footnotes' ) ) );
That is consistent with note #‌5 in https://developer.wordpress.org/reference/functions/__/

But the “it will interfere in automatic parsing of your plugin/theme’s files for translation” is incorrect, since Footnotes does have POT file and translations. Moreover @lolzim just recently re-generated a POT file. 

So, at most, WP could say it **may** interfere, perhaps in a buggy tool, **not** Gettext.

OTOH I wonder why the plugin name is stored in a constant, as opposed to the public name that involves HTML markup and is a good fit for a constant.

Should we add a comment somewhere in the codebase?

2021-02-24 17:14 UTC, pewgeuges requested changes
This branch cannot be merged as-is. Just fixed the broken internal script 0dc5f23123231465b675c4872b637ec2070dacb4

I stopped copy-pasting from VSCodeX in GitHub’s editor when @Rumperuu fixed the EOL issue, and don’t use it any longer since Git CLI works for me.

2021-02-24 21:28 UTC, Rumperuu commented on class/hooks.php
> +			wp_die( wp_kses_post( __( 'You do not have permission to run this script.', 'footnotes' ) ) );
I'm not super familiar with WordPress internationalisaton, but in the scope of this PR just replacing the constant with a string literal is functionally identical and avoids PHPCS warnings (without having to suppress them) so it should be fine for now. Unless we can lose the second argument altogether and just use the default (‘default’)?

Outside the scope of this PR, I agree that having a constant for just ‘footnotes’ is unnecessary. For one, the name of the Plugin is highly unlikely to change in future, and even if it did, running `s/'footnotes'/'new_plugin_name'/g` would be just as easy as changing the value of a constant. If we were doing some fancy HTML marking-up  (i.e., using the value of `$l_str_linked_name` from `class/task.php:1046`) then maybe it would make more sense for brevity.

2021-02-24 21:39 UTC, Rumperuu commented on class/task.php
> +	public static $a_bool_alternative_tooltips_enabled = false;
Unless I'm missing something, every reference to `$a_bool_alternative_tooltips_enabled` in `class/init.php` or `class/task.php` is prefaced with `self::`, which means that despite having the same name each variable is entirely distinct (i.e., the first is `MCI_Footnotes::$a_bool_alternative_tooltips_enabled` and the second is `MCI_Footnotes_Task::$a_bool_alternative_tooltips_enabled`). As a result, either both class properties should be declared as `private` OR one class should have the `public` declaration and the other should call that class's public property.

2021-02-24 21:40 UTC, Rumperuu commented on class/task.php
> +	 * Footnote delimiter syntax validation.
If a future refactor means that they need to be public class properties again, we can re-implement that at the time.

2021-02-24 21:57 UTC, Rumperuu commented on class/template.php
> - * @lastmodified 2021-02-18T2024+0100
Looks good, although I've removed the datetime from the `@since` tag and the `@lastmodified` tag in 8a0658c

`@lastmodified` tags are unnecessary. There are others elsewhere in the codebase that can be deleted as we go, but in the interests of getting this PR merged so that general development can re-commence please ignore them for now.

2021-02-24 22:02 UTC, Rumperuu commented on class/hooks.php
> +			wp_die( wp_kses_post( __( 'You do not have permission to run this script.', 'footnotes' ) ) );
From @lolzim:

> Should that change the languages status in https://translate.wordpress.org/projects/wp-plugins/footnotes/ ?

2021-02-24 22:03 UTC, Rumperuu commented on class/hooks.php
> +			wp_die( wp_kses_post( __( 'You do not have permission to run this script.', 'footnotes' ) ) );
Removing the second argument and relying on the default value looks like it won't work, so let's stick with the string literal.

2021-02-24 22:24 UTC, pewgeuges commented
**Git CLI** only works as long as the remote branch is not modified. As soon as it shoud update like `svn up`, I can command whatever `git pull origin wp-coding-standard--fresh`, it displays a mess and is not even capable of accepting the `Y` (or `N`) it itself asks me for.

2021-02-24 23:10 UTC, pewgeuges reviewed
A workaround is to edit a **copy** of the local clone, then update the clone remotely, track changes, and update locally to commit, like with SVN.
The disorder happened because I edited directly my local clone.

2021-02-25 00:42 UTC, pewgeuges commented on class/task.php
> +	public static $a_bool_alternative_tooltips_enabled = false;
That (2) is intended. There has been a bug ([tooltips not showing up in popups](https://wordpress.org/support/topic/footnotes-use-in-popup-maker/#post-13983426)) though assigning a variable after calling it, and first we must find out which instance, in class/init.php or class/task.php is assigned first.

2021-02-25 00:48 UTC, pewgeuges commented on class/task.php
> +	 * Footnote delimiter syntax validation.
> If a future refactor means that they need to be public class properties again, we can re-implement that at the time.

I was wrong. These are used both in search() and in reference_container().

2021-02-25 07:49 UTC, Rumperuu commented
> **Git CLI** only works as long as the remote branch is not modified. As soon as it should update like `svn up`, I can command whatever `git pull origin wp-coding-standard--fresh`, it displays a mess and is not even capable of accepting the `Y` (or `N`) it itself asks me for.

Things get a bit messy if your local branch and the remote branch diverge. Always use `git pull` before you start working on something to make sure you're up-to-date with the remote. If you have outstanding local edits to any files and `git pull` pulls down other edits to the same files, you may get a merge conflict that you'll have to fix manually, which I think it what you're referring to. Fixing a merge conflict acts the same as any other commit, you can use `git status` to see which file(s) are having problems, edit them as normal (you'll see the problem section(s) of code bracketed with `=======HEAD` or something similar) and when you're done you stage and commit them to complete the pull.

I'm not making any more commits though so you should be fine for the rest of the branch review. I'm going to codify some of the learning points from the experience of this PR into `CONTRIBUTING.md` as well, so hopefully future development work runs a little smoother!

2021-02-25 12:54 UTC, pewgeuges commented
Thank you @Rumperuu.

> Things get a bit messy if your local branch and the remote branch diverge.

I think that my copy of Git CLI adds problems of its own.

> Always use `git pull` before you start working on something to make sure you're up-to-date with the remote.

I’ve noticed that then, I need to make immediately two copies:
1. A backup copy.
2. A draft copy.

When done drafting, I need to `git pull` again. If Git outputs `Already up-to-date.`, I can go ahead. If not, I need to make a new backup copy, then diff (or diff-filelist, then diff in VSCode if it’s too much for a plain text line diff) the updated clone and the draft against the previous backup copy. Either import the changes to the draft, or add the drafted edits to a new draft. Iterate until a window of opportunity opens. Rush copy-pasting the draft over the clone, `git add .`, `git commit -m "Headline." -m "Message body (may contain 
line 
breaks).", and `git push` immediately. Because if other changes are committed-pushed in the meantime, updating the clone will fail, and then I’m currently having no other option than to close the terminal and delete the clone as out of service.

> If you have outstanding local edits to any files and `git pull` pulls down other edits to the same files, you may get a merge conflict that you'll have to fix manually, which I think it what you're referring to. 

Yes but moreover, I’m reporting something that looks like a real bug.

> Fixing a merge conflict acts the same as any other commit, you can use `git status` to see which file(s) are having problems, edit them as normal; you'll see the problem section(s) of code bracketed like this:
[…]

I’m unable to input any command. It’s out of order.

> Then when you're done you stage and commit them to complete the pull. More info [here](https://opensource.com/article/20/4/git-merge-conflict).

Thanks for the tutorial and the resource. Yet I seem to be using another Git client than what all this is referring to.

> I'm not planning to make any more commits to this branch though so you should be fine for the rest of your review.

Thanks. Turned out I’m done reviewing, as the files reviewed after my last commit-push are very short. I’ve just refrained from checking the 30st file as viewed, afraid that could trigger an automatic merger. I’m now testing the current status, and I’m having a tooltip outage that also affects previous versions, despite settings are OK. Thankfully I see that users are still having working tooltips, both jQuery UI and JS-CSS, using current v2.5.6.

> I'm going to codify some of the learning points from the experience of this PR into `CONTRIBUTING.md` as well, so hopefully future development work runs a little smoother!

Thanks a lot for this too. Still, if at my end it’s also a software issue…

2021-02-25 13:39 UTC, pewgeuges commented
> […] make immediately two copies:
> 
> 1. A backup copy.
> 2. A draft copy.
> 
> […] Rush copy-pasting the draft over the clone

Need perhaps to mention that this “draft” does not contain the following files, deleted in the draft copy using this script:
```bash
#!/bin/bash
# 2021-02-25T1128+0100
# gwp.sh
# Previously: GW-prepare.sh
# Deletes Git-specific and not-to-edit files in workbench copy of local clone.
rm -rf GW/.git
rm -rf GW/.github
rm -rf GW/contrib
rm -rf GW/docs
rm -rf GW/_tools
rm -rf GW/composer.json
rm -rf GW/composer.lock
rm -rf GW/CONTRIBUTING.md
rm -rf GW/LICENSE
rm -rf GW/README.md
rm -rf GW/SECURITY.md
rm -rf GW/.gitignore
```

2021-02-25 14:43 UTC, Rumperuu commented
> Thanks. Turned out I’m done reviewing, as the files reviewed after my last commit-push are very short. I’ve just refrained from checking the 30st file as viewed, afraid that this could trigger an automatic merger.

Not to worry; once you check off the final file I can handle the merge—it won't do it automatically.

2021-02-25 14:56 UTC, pewgeuges commented
> > […] I’ve just refrained from checking the 30st file as viewed, afraid that this could trigger an automatic merger.
> 
> Not to worry; once you check off the final file I can handle the merge—it won't do it automatically.

Thanks. Just finished checking all 30.

I’m still having to test it.

2021-02-25 18:03 UTC, pewgeuges commented
I’m done reviewing and testing. Everything okay for me!

2021-02-25 18:04 UTC, pewgeuges approved these changes

2021-02-25 19:17 UTC, merged