Automatically generate new releases
markcheret/footnotes pull request #59
Opened 2021-03-10 14:57 UTC by Rumperuu

This PR begins the process of automating our release workflow via GitHub Actions.

This PR adds a series of actions that run when a new release is issued. You can see an example release [here](https://github.com/markcheret/footnotes/releases/tag/workflow-test-2) and its related workflow results [here](https://github.com/markcheret/footnotes/actions/runs/639980408).

The actions:

1. checkout the code
2. run the Composer `build` command, which copies only build-appropriate files into the `dist/` directory
    - NB you will have to have already manually minified the stylesheets and placed them in `dist/css/` before running the `build` command
3. zips those files into an archive, appended with the tag name
4. uploads that zipfile as an artifact (NB this isn't currently used for anything, but might be useful later)
5. uploads that same zipfile to the release.

This PR does **not** do anything with the WordPress Plugin Directory. An action to do so _is_ in the file, but is currently commented out. For the time being, we can use this to generate new releases and then upload them manually.

This also does **not** perform any sanity-checking of version numbers etc. Garbage in will lead to garbage out.

Part of #30

2021-03-10 19:54 UTC, pewgeuges reviewed
This does not conflict with the `fixcomments` branch currently in progress, and only affects new files, that need to be completed since they’re now part of the package.

As of the expected output, it may only be used for test purposes. But these tests are irrelevant because we cannot invoke them in user support, nor share them on the Forum, as opposed to testing the actual codebase as committed to SVN, that shall be released.

I see a point of release automation in versioning and timestamping all files, notably the readmes, the main PHP file, the stylesheets, and why not all PHP files.

The stylesheets however need to be concatenated and minified before the release. Currently they’re concatenated by running `development/csscat.sh`, then the 12 files are minified (using VSCode plugin), then csscat is run again to move minified and delete concatenated. 

Overall in the actual size and state of the plugin and the release environment, I’m however missing the point of release automation though, sorry for that.

I won’t be approving this and I’ll be waiting for @markcheret’s decision making, whether he wants the plugin codebase to support this enhancement, with respect to Footnotes’ new GitHub repository, and with respect to the historic SVN repository.

2021-03-10 23:21 UTC, pewgeuges requested changes
Why should the plugin stop shipping the folder development/? Was this ever discussed?

Contains use of the template stack, the added PHPDOC tags, and the stylesheet processing script.

The point in shipping this folder is similar to the point in providing unminified files alongside.

2021-03-10 23:21 UTC, pewgeuges commented on .distignore
> +LICENSE
Do we really intend to not include these files in the plugin?

What about these changelog items:

- Adding: Documentation: additional readme in markdown format 'README.md' for use with GitHub, thanks to @rumperuu code contribution.
- Adding: Documentation: help and support for contributors by the means of Contributing Guidelines 'CONTRIBUTING.md', thanks to @rumperuu code contribution.
- Adding: Development: pre-commit hook for WordPress projects, modified from @bjornjohansen, thanks to @rumperuu code contribution.

My thought is that Footnotes’ users should be able to access these files in their WP instance.

2021-03-10 23:21 UTC, pewgeuges commented on _tools/build.sh
> +cp -r -t dist class/ css/ js/ img/ languages/ templates/
The folder development/ is included in the plugin.

2021-03-10 23:25 UTC, pewgeuges commented
Ended up taking time to review these files too. Turns out I was drafting an out-of-sync changelog, and making empty promises after the development/ folder already included in the plugin is now going to be deleted for release…

2021-03-11 05:37 UTC, pewgeuges commented
#60 deletes the development/ folder and moves 2 docs to root, CSS handling script to css/, so the dist/ script would need changes?

I think I’m expected to be going to fix this directly, but rather wait for your feedback @Rumperuu @markcheret @lolzim

2021-03-11 11:26 UTC, Rumperuu commented on .distignore
> +LICENSE
The content of `LICENSE` is duplicated in `licence.txt` which is included in the distrtibution (although if the WP Plugin Directory can handle Markdown then we could combine them into a single `LICENSE` file).

`CONTRIBUTING.md` and `SECURITY.md` are intended for people who come across this repo. here, without the context of the WP Plugin Directory (which displays `readme.txt`). I've been hesitant to change `readme.txt` yet as we're still getting this repo. + workflow set up, but once we're happy that everything's set up properly here, we can change `readme.txt` to point people interested in contributing to the `CONTRIBUTING.md` file here, and add a new pinned post to the Support Forum that includes the content of `SECURITY.md`.

`README.md` is currently mostly a clone of `readme.txt`, but my intention is to edit it to be a more distinct 'readme-for-developers' rather than `readme.txt`, which is primarily a 'readme-for-users' due to where it gets displayed.

2021-03-11 11:27 UTC, Rumperuu commented on _tools/build.sh
> +cp -r -t dist class/ css/ js/ img/ languages/ templates/
Fixed in 37de2a1

2021-03-11 11:47 UTC, Rumperuu commented
> As of the expected output, it may only be used for test purposes. But these tests are irrelevant because we cannot invoke them in user support, nor share them on the Forum, as opposed to testing the actual codebase as committed to SVN, that shall be released.

Not sure what you mean here.
 
> I see a point of release automation in versioning and timestamping all files, notably the readmes, the main PHP file, the stylesheets, and why not all PHP files.
> 
> Overall in the actual size and state of the plugin and the release environment, I’m however missing the point of release automation though, sorry for that.

The point is that, once we're happy that we want to issue a new release, we can just make a release on GitHub, download and extract the resulting zip into our test environments and then (assuming everything works fine) stick the contents of the the zip into `tags/<version number>` on the SVN and update the ‘Stable Tag’ in `trunk/readme.txt` to point to it.

That might not sound world-changing just yet, but the ultimate goal is to have all of the steps between clicking ‘Create new release’ and ‘New release distributed to users via WP Plugin Directory’ automated. That means: 

1. file minification
2. automated unit testing
3. error-checking (e.g., that version numbers are all correct)
4. updating changelog
5. uploading to SVN

Which both makes the whole process easy peasy and will mitigate the risk of human error like the other week.

2021-03-11 12:25 UTC, pewgeuges submitted a review, later dismissed
> > As of the expected output, it may only be used for test purposes. But these tests are irrelevant because we cannot invoke them in user support, nor share them on the Forum, as opposed to testing the actual codebase as committed to SVN, that shall be released.
> 
> Not sure what you mean here.

As you mentioned the other week, final tests are only valid if the code is from SVN trunk/.

> 
> > I see a point of release automation in versioning and timestamping all files, notably the readmes, the main PHP file, the stylesheets, and why not all PHP files.
> > Overall in the actual size and state of the plugin and the release environment, I’m however missing the point of release automation though, sorry for that.
> 
> The point is that, once we're happy that we want to issue a new release, we can just make a release on GitHub, download and extract the resulting zip into our test environments and then (assuming everything works fine) stick the contents of the the zip into `tags/<version number>` on the SVN and update the ‘Stable Tag’ in `trunk/readme.txt` to point to it.

Making the release on GitHub doesn’t make sense to me. We already have a working copy, so the scripts may be run locally, and the result committed to SVN trunk/.

The release is not sticked in a tag folder but in trunk/, then trunk/ is copied to a tag via SVN.

The Stable Tag is not updated after creating the tag folder. It is updated in trunk locally, then the tag is made with the exact same information in it, then the final commit is the release.

> 
> That might not sound world-changing just yet, but the ultimate goal is to have all of the steps between clicking ‘Create new release’ and ‘New release distributed to users via WP Plugin Directory’ automated. That means:
> 
> 1. file minification
> 2. automated unit testing
> 3. version number updates

That’s where bugs can happen.

> 4. updating changelog

There is no way to autogenerate the changelog.

> 5. uploading to SVN

That step shouldn’t be automated, since we need to test the content of trunk/ before releasing it.

Trying to fully automate the whole process exposes the Community to the risk of bugs and to overconfidence making them happen.

> 
> Which both makes the whole process easy peasy and will mitigate the risk of human error like the other week.

The source of error is shifted, not eliminated. Mitigating the risk doesn’t mean it’s eliminated. 

We need a zero error guarantee from now on.

2021-03-11 12:50 UTC, Rumperuu commented on readme.txt
`.distignore` isn't actually used for anything yet, so if you want to include `CONTRIBUTING.md` etc. in `dist/` then they need to to into `build.sh`

2021-03-11 12:56 UTC, Rumperuu commented
> > > I see a point of release automation in versioning and timestamping all files, notably the readmes, the main PHP file, the stylesheets, and why not all PHP files.
> > > Overall in the actual size and state of the plugin and the release environment, I’m however missing the point of release automation though, sorry for that.
> > 
> > The point is that, once we're happy that we want to issue a new release, we can just make a release on GitHub, download and extract the resulting zip into our test environments and then (assuming everything works fine) stick the contents of the the zip into `tags/<version number>` on the SVN and update the ‘Stable Tag’ in `trunk/readme.txt` to point to it.
> 
> Making the release on GitHub doesn’t make sense to me. We already have a working copy, so the scripts may be run locally, and the result committed to SVN trunk/.

The end result of all this will be that, for all intents and purposes, we can forget about the SVN repo. It will effectively be a mirror of this repo., where creating a new release here ripples down to there if appropriate (I intend to have the actual 'deploy to WP Plugin Directory' GitHub Action run on-demand, rather than automatically, so only releases that we actively choose to push to the SVN (i.e., x.0.0 and 0.x.0 releases) will do so.

> > 1. uploading to SVN
> 
> That step shouldn’t be automated, since we need to test the content of trunk/ before releasing it.
>
> Trying to fully automate the whole process exposes the Community to the risk of bugs and to overconfidence making them happen.

You're right, see above.

> > Which both makes the whole process easy peasy and will mitigate the risk of human error like the other week.
> 
> The source of error is shifted, not eliminated. Mitigating the risk doesn’t mean it’s eliminated.
> 
> We need a zero error guarantee from now on.


As nice as it would be, this is an unachievable goal. Steps like automating the release process are are intended precisely to shift the risk of human error, which is unpredictable, to the risk of process misconfiguration, which is more predictable, as well as easier to remedy and fix.

2021-03-11 12:59 UTC, pewgeuges commented on .distignore
> +LICENSE
@Rumperuu @markcheret @lolzim 

Sorry for including LICENSE in the comment. I left it in `.distignore`.

As of the 3 items deleted from `.distignore`, they need to be included in the next versions of Footnotes. 

Later on, these files can be handled as designed.

If the Footnotes Community didn’t have to go through the 2.5.9d1 accident, we wouldn’t need to apologize. Including these files in the distributed package **and mentioning them in the changelog** is part of our apologies.

Does that make sense to everyone?

2021-03-11 13:08 UTC, pewgeuges commented
> > The source of error is shifted, not eliminated. Mitigating the risk doesn’t mean it’s eliminated.
> > We need a zero error guarantee from now on.
> 
> As nice as it would be, this is an unachievable goal. Steps like automating the release process are are intended precisely to shift the risk of human error, which is unpredictable, to the risk of process misconfiguration, which is more predictable, as well as easier to remedy and fix.

We need the ability to have dry runs to validate the process, like in a branch in SVN or so. 

The first time the process runs mustn’t be for code to be released.

Remember the tester’s axiom: **If it isn’t tested, consider it’s broken.**

2021-03-11 13:20 UTC, pewgeuges commented on readme.txt
@Rumperuu 

Thanks, done in cb561fe0800ea1a2d21da9af7fb9ae1019b68f3a

2021-03-12 02:20 UTC, markcheret commented
I have never seen the branches folder used on WordPress SVN, so that could be an amazing test for this! I don't know what they're used for, though.

2021-03-12 04:21 UTC, pewgeuges commented
> I have never seen the branches folder used on WordPress SVN, so that could be an amazing test for this! I don't know what they're used for, though.

Per the *Plugin Handbook*, *Using Subversion* section, [Branches](https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/#branches):
```
The /branches directory is a place that you can use to store 
branches of the plugin. Perhaps versions that are in 
development, or test code, etc.
```

2021-03-12 04:22 UTC, pewgeuges commented
@markcheret 

> I have never seen the branches folder used on WordPress SVN, so that could be an amazing test for this! I don't know what they're used for, though.

Per the *Plugin Handbook*, *Using Subversion* section, [Branches](https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/#branches):
```
The /branches directory is a place that you can use to store 
branches of the plugin. Perhaps versions that are in 
development, or test code, etc.
```

2021-03-12 04:35 UTC, pewgeuges commented
@Rumperuu 

The `compliance` label was added for some reason, as we should be careful to stay compliant when setting up processes while we don’t control how WordPress manages the plugin ecosystem.

Just a few samples from [Using Subversion](https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/):
[quote]
Create tags from trunk #Create tags from trunk
Instead of pushing your code directly to a tag folder, you should edit the code in trunk, complete with the stable version in the readme, and then copy the code from trunk to the new tag.

Not only will this make it easier see any changes, you will be making smaller commits as SVN will only update the changed code.

If you are operating locally, then you can update trunk and create tags from it all in one go. Checkout the root of your repository, update the files in /trunk, then svn copy /trunk /tags/1.2.3 (or whatever the version number is) and then commit the whole thing in one go. SVN is a system based on differences, and as long as you use svn to do the copy operation, then it preserves history and makes everything easy for others to follow along with.

Many people use trunk as a placeholder. While it’s possible to simply update the readme.txt file in trunk and put everything in tag folders, doing so makes it more difficult to compare any changes in your code. Instead, trunk should contain the latest version of your code, even if that version is a beta.
[/quote]

I was sometimes afraid that we’re forgetting about some aspects.

2021-03-12 04:51 UTC, pewgeuges reviewed
Reviewed after syncing readme and footnotes.php with WP5.7 branch.

As announced, no approval. Looking out for @markcheret’s and @lolzim’s approval.

2021-03-12 09:47 UTC, Rumperuu commented
> @markcheret
> 
> > I have never seen the branches folder used on WordPress SVN, so that could be an amazing test for this! I don't know what they're used for, though.
> 
> Per the _Plugin Handbook_, _Using Subversion_ section, [Branches](https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/#branches):
> 
> ```
> The /branches directory is a place that you can use to store 
> branches of the plugin. Perhaps versions that are in 
> development, or test code, etc.
> ```

Sounds like an ideal use for branches then!

> @Rumperuu
> 
> The `compliance` label was added for some reason, as we should be careful to stay compliant when setting up processes while we don’t control how WordPress manages the plugin ecosystem.

Equally, it was removed for a reason. This has nothing to do with adherence to the WP Coding Standards.

2021-03-12 10:33 UTC, markcheret commented
well then, let's test the deployment to a testing branch then!

2021-03-12 10:37 UTC, markcheret approved these changes
No clue about the code changes.
Approval for the build/deploy scripts to build artefacts and push to a testing branch on WordPress SVN

2021-03-12 11:00 UTC, Rumperuu commented
> No clue about the code changes.
> Approval for the build/deploy scripts to build artefacts and push to a testing branch on WordPress SVN

I'll treat this as a two-approval PR and wait for @lolzim's response before merging.

> well then, let's test the deployment to a testing branch then!

We can do this in a separate PR; the [10up deployment action](https://github.com/10up/action-wordpress-plugin-deploy) deploys straight to `trunk/` and copies to `tags/<new-tag>/`, so I'm thinking we can have another action that runs whenever we merge a branch with `main` that `rsync`s all of the files into `branch/dev/` (or whatever we call the branch) on the SVN.

That way, we'll always know that `main` === `branch/dev/`, and when we're happy that it's ready for release we can trigger that on GitHub and the action will automatically set `trunk/` === `main`and `tags/<version>/` === `trunk/`.

@pewgeuges You're more au fait with the SVN than I am, so I'll let you set up the branch.

2021-03-12 13:14 UTC, lolzim approved these changes
ok for me

2021-03-12 17:52 UTC, Rumperuu reviewed
+1

2021-03-12 17:53 UTC, merged

2021-03-12 18:24 UTC, pewgeuges commented
@Rumperuu 

> > The `compliance` label was added for some reason, as we should be careful to stay compliant when setting up processes while we don’t control how WordPress manages the plugin ecosystem.
> 
> Equally, it was removed for a reason. This PR has nothing to do with adherence to the WP Coding Standards.

Sorry, I forgot about the label’s narrow scope and overstretched its semantics. Thanks for removing it!